// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqvH5TMAf3Hwhl82AAZgRAvk7dFQTMdBg',
    appId: '1:154301754198:web:7b99d19903dda2a7cc44f7',
    messagingSenderId: '154301754198',
    projectId: 'app-hackatlon-8346a',
    authDomain: 'app-hackatlon-8346a.firebaseapp.com',
    storageBucket: 'app-hackatlon-8346a.firebasestorage.app',
    measurementId: 'G-9G7JYM7434',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQAThVLiiFRO2HBNhuZilUqqiWIbY3mxM',
    appId: '1:154301754198:android:4095824ee43b9dddcc44f7',
    messagingSenderId: '154301754198',
    projectId: 'app-hackatlon-8346a',
    storageBucket: 'app-hackatlon-8346a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzlK3gy8ZeJ3hypz4xv3EKKf9-Fnc8Jo',
    appId: '1:154301754198:ios:f689344fd9946d93cc44f7',
    messagingSenderId: '154301754198',
    projectId: 'app-hackatlon-8346a',
    storageBucket: 'app-hackatlon-8346a.firebasestorage.app',
    iosBundleId: 'com.example.alquilerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTzlK3gy8ZeJ3hypz4xv3EKKf9-Fnc8Jo',
    appId: '1:154301754198:ios:f689344fd9946d93cc44f7',
    messagingSenderId: '154301754198',
    projectId: 'app-hackatlon-8346a',
    storageBucket: 'app-hackatlon-8346a.firebasestorage.app',
    iosBundleId: 'com.example.alquilerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqvH5TMAf3Hwhl82AAZgRAvk7dFQTMdBg',
    appId: '1:154301754198:web:7ae9ff4076b8215ccc44f7',
    messagingSenderId: '154301754198',
    projectId: 'app-hackatlon-8346a',
    authDomain: 'app-hackatlon-8346a.firebaseapp.com',
    storageBucket: 'app-hackatlon-8346a.firebasestorage.app',
    measurementId: 'G-X2E38SZ951',
  );

}